// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqAiJFelnAHhbVGbFgvLuS-E0kQR7cDus',
    appId: '1:557637637607:web:b2e97ec66efba967dc5942',
    messagingSenderId: '557637637607',
    projectId: 'capstone-4e202',
    authDomain: 'capstone-4e202.firebaseapp.com',
    storageBucket: 'capstone-4e202.appspot.com',
    measurementId: 'G-5Y22TM0G4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNhM9paVYVmas4u1bwUV5h0KMByLsodBo',
    appId: '1:557637637607:android:4a301d4d69415c0fdc5942',
    messagingSenderId: '557637637607',
    projectId: 'capstone-4e202',
    storageBucket: 'capstone-4e202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3vLPdn0A_k_k5c9YQ2JT6yJLGD1U9h0w',
    appId: '1:557637637607:ios:4cb223bacfd5f11cdc5942',
    messagingSenderId: '557637637607',
    projectId: 'capstone-4e202',
    storageBucket: 'capstone-4e202.appspot.com',
    iosClientId: '557637637607-dvgs5htd0pdsch3u35imtq8vfq2cfpb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3vLPdn0A_k_k5c9YQ2JT6yJLGD1U9h0w',
    appId: '1:557637637607:ios:4cb223bacfd5f11cdc5942',
    messagingSenderId: '557637637607',
    projectId: 'capstone-4e202',
    storageBucket: 'capstone-4e202.appspot.com',
    iosClientId: '557637637607-dvgs5htd0pdsch3u35imtq8vfq2cfpb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );
}
